### DISCUSSION TITLE
[TEST ENV.] Acces via url like a prod. enviroment?

### DISCUSSION THREAD

**Discussion by Mat-moran** [Tecnativa/doodba#373] [Q&A] [answered]
Hi I need to give access to the ```test``` enviroment to the world,

I have the **inverseproxy configured and running** like in the prod enviroment but I can not access to my server via website url.

Any special configuration have to be done in order to have it running?

My wesite is saying ```The page isn't working. www.website.com redirected you too many times```

Thanks and regards.
Amadeo

**Comment by obayit** [comment]
Hi, can you provide more information:
 - your answer for the test domains
 - what is your edge proxy? are you using traefik behind nginx for example?

**Reply by Mat-moran** [reply]
Hi @obayit ,

I am using the default confiuration for everything:

- traefik V1 (without nginx or anything else, just the default values of the copier answer + the domain name. The domain DNS are pointing to the IP where I have the instance)
Answer to ```domain_test``` -> ``` [hosts:[www.website.es]]```

Thanks! :smile:

**Reply by yajo** [reply]
Please paste your `.copier-answers.yml` and your `test.yaml`

**Reply by Mat-moran** [reply]
Hi @Yajo  here are the files:

**.copier-answers.yml**
```yaml
# Changes here will be overwritten by Copier
_commit: v2.6.1
_src_path: gh:Tecnativa/doodba-copier-template
backup_deletion: false
backup_dst: boto3+s3://dmodoo.dminternational.bkup
backup_email_from: amg@davidmoran.net
backup_email_to: amg@davidmoran.net
backup_tz: UTC
cidr_whitelist: null
domains_prod:
  - hosts:
      - www.dminternational.es
domains_test:
  - hosts:
      - www.test.dminternational.es
gitlab_url: https://gitlab.com/Moran-Guerrero/dmodoo-dminternational.git
odoo_dbfilter: .*
odoo_initial_lang: es_ES
odoo_listdb: true
odoo_oci_image: null
odoo_proxy: traefik
odoo_version: 14.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_username: odoo
postgres_version: 13
project_author: David Moran S.A.
project_license: BSL-1.0
project_name: dmodoo-dminternational
smtp_canonical_default: davidmoran.net
smtp_canonical_domains: null
smtp_default_from: amg@davidmoran.net
smtp_relay_host: smtp.gmail.com
smtp_relay_port: 587
smtp_relay_user: amg@davidmoran.net
```

**test.yaml**
```yaml
version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-test}"
      # To install demo data export DOODBA_WITHOUT_DEMO=false
      WITHOUT_DEMO: "${DOODBA_WITHOUT_DEMO-all}"
      SMTP_PORT: "1025"
      SMTP_SERVER: smtplocal
    restart: unless-stopped
    depends_on:
      - db
      - smtp
    networks:
      default:
      globalwhitelist_shared:
      inverseproxy_shared:
    labels:
      doodba.domain.main: "www.test.dminternational.es"
      traefik.enable: "true"
      traefik.domain: "www.test.dminternational.es"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule: Host:www.test.dminternational.es;Path:/{anything:.*}
      traefik.longpolling-0.frontend.rule: Host:www.test.dminternational.es;Path:/longpolling/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.http.services.dmodoo-dminternational-14-0-test-main.loadbalancer.server.port: 8069
      traefik.http.services.dmodoo-dminternational-14-0-test-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.dmodoo-dminternational-14-0-test-longpolling-0.rule:
        Host(`www.test.dminternational.es`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.dmodoo-dminternational-14-0-test-longpolling-0.service: dmodoo-dminternational-14-0-test-longpolling
      traefik.http.routers.dmodoo-dminternational-14-0-test-longpolling-0.middlewares: dmodoo-dminternational-14-0-test-forceSecure
      traefik.http.routers.dmodoo-dminternational-14-0-test-longpolling-secure-0.rule:
        Host(`www.test.dminternational.es`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.dmodoo-dminternational-14-0-test-longpolling-secure-0.service: dmodoo-dminternational-14-0-test-longpolling
      traefik.http.routers.dmodoo-dminternational-14-0-test-longpolling-secure-0.middlewares: dmodoo-dminternational-14-0-test-forceSecure
      traefik.http.routers.dmodoo-dminternational-14-0-test-longpolling-secure-0.tls: "true"
      traefik.http.routers.dmodoo-dminternational-14-0-test-longpolling-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.dmodoo-dminternational-14-0-test-forbiddenCrawlers-0.rule:
        Host(`www.test.dminternational.es`) && (PathPrefix(`/`))
      traefik.http.routers.dmodoo-dminternational-14-0-test-forbiddenCrawlers-0.service: dmodoo-dminternational-14-0-test-main
      ? traefik.http.routers.dmodoo-dminternational-14-0-test-forbiddenCrawlers-0.middlewares
      : dmodoo-dminternational-14-0-test-buffering,
        dmodoo-dminternational-14-0-test-compress,
        dmodoo-dminternational-14-0-test-forbid-crawlers,
        dmodoo-dminternational-14-0-test-forceSecure
      ? traefik.http.routers.dmodoo-dminternational-14-0-test-forbiddenCrawlers-secure-0.rule
      : Host(`www.test.dminternational.es`) && (PathPrefix(`/`))
      traefik.http.routers.dmodoo-dminternational-14-0-test-forbiddenCrawlers-secure-0.service: dmodoo-dminternational-14-0-test-main
      ? traefik.http.routers.dmodoo-dminternational-14-0-test-forbiddenCrawlers-secure-0.middlewares
      : dmodoo-dminternational-14-0-test-buffering,
        dmodoo-dminternational-14-0-test-compress,
        dmodoo-dminternational-14-0-test-forbid-crawlers,
        dmodoo-dminternational-14-0-test-forceSecure
      traefik.http.routers.dmodoo-dminternational-14-0-test-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.dmodoo-dminternational-14-0-test-forbiddenCrawlers-secure-0.tls.certResolver: letsencrypt
    command:
      - odoo
      - --workers=2
      - --max-cron-threads=1

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped

  smtp:
    extends:
      file: common.yaml
      service: smtpfake
    restart: unless-stopped
    networks:
      default:
        aliases:
          - smtplocal
      inverseproxy_shared:
    labels:
      doodba.domain.main: "www.test.dminternational.es"
      traefik.docker.network: "inverseproxy_shared"
      traefik.enable: "true"
      traefik.frontend.passHostHeader: "true"
      traefik.mailhog-0.frontend.rule: Host:www.test.dminternational.es;PathPrefixStrip:/smtpfake/
      traefik.mailhog-0.port: 8025
      # Mailhog service
      traefik.http.middlewares.dmodoo-dminternational-14-0-test-mailhog-stripprefix.stripPrefix.prefixes: /smtpfake/
      traefik.http.services.dmodoo-dminternational-14-0-test-mailhog.loadbalancer.server.port: 8025
      ? traefik.http.middlewares.dmodoo-dminternational-14-0-test-buffering.buffering.retryExpression
      : IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.dmodoo-dminternational-14-0-test-compress.compress: "true"
      ? traefik.http.middlewares.dmodoo-dminternational-14-0-test-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag
      : "noindex, nofollow"
      traefik.http.middlewares.dmodoo-dminternational-14-0-test-forceSecure.headers.forceSTSHeader: "true"
      traefik.http.middlewares.dmodoo-dminternational-14-0-test-forceSecure.headers.sslRedirect: "true"
      traefik.http.routers.dmodoo-dminternational-14-0-test-mailhog-0.rule:
        Host(`www.test.dminternational.es`) && PathPrefix(`/smtpfake/`)
      traefik.http.routers.dmodoo-dminternational-14-0-test-mailhog-0.service: dmodoo-dminternational-14-0-test-mailhog
      traefik.http.routers.dmodoo-dminternational-14-0-test-mailhog-0.middlewares:
        dmodoo-dminternational-14-0-test-buffering,
        dmodoo-dminternational-14-0-test-compress,
        dmodoo-dminternational-14-0-test-forbid-crawlers,
        dmodoo-dminternational-14-0-test-forceSecure,
        dmodoo-dminternational-14-0-test-mailhog-stripprefix
      traefik.http.routers.dmodoo-dminternational-14-0-test-mailhog-secure-0.rule:
        Host(`www.test.dminternational.es`) && PathPrefix(`/smtpfake/`)
      traefik.http.routers.dmodoo-dminternational-14-0-test-mailhog-secure-0.service: dmodoo-dminternational-14-0-test-mailhog
      ? traefik.http.routers.dmodoo-dminternational-14-0-test-mailhog-secure-0.middlewares
      : dmodoo-dminternational-14-0-test-buffering,
        dmodoo-dminternational-14-0-test-compress,
        dmodoo-dminternational-14-0-test-forbid-crawlers,
        dmodoo-dminternational-14-0-test-forceSecure,
        dmodoo-dminternational-14-0-test-mailhog-stripprefix
      traefik.http.routers.dmodoo-dminternational-14-0-test-mailhog-secure-0.tls: "true"
      traefik.http.routers.dmodoo-dminternational-14-0-test-mailhog-secure-0.tls.certResolver: letsencrypt
    volumes:
      - "smtpconf:/etc/mailhog:ro,z"
    entrypoint: [sh, -c]
    command:
      - test -r /etc/mailhog/auth && export MH_AUTH_FILE=/etc/mailhog/auth; exec MailHog

networks:
  default:
    internal: true
    driver_opts:
      encrypted: 1

  globalwhitelist_shared:
    external: true

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:
  smtpconf:
```
