### DISCUSSION TITLE
Help with repo.yaml config

### DISCUSSION THREAD

**Discussion by rquevedo** [Tecnativa/doodba#382] [Q&A] [answered]
Hi folks,
I have read the documentation and repo.yaml and addons.yaml are ready to use many repos and addons but always addons directly inside repos. There are any way to configure addons inside a repository folder? For example:
gtihub.com/myuser/myrepo
Then:
myrepo/partner1
myrepo/partner2
myrepo/partnerN

And i want to use only addons for partner1

Thanks in advance.

**Comment by joao-p-marques** [comment, marked as answer]
Yes, you can add a custom repo on `repos.yaml`:
```yaml
./my_repo:
  defaults:
    depth: $DEPTH_DEFAULT
  remotes:
    my_remote: https://github.com/my_org/my_repo
  target: my_branch $ODOO_VERSION
  merges:
    - my_branch $ODOO_VERSION
```
and then reference a specific folder in `addons.yaml`:
```yaml
./my_repo/some_folder:
  - some_module
  - some_other_module
```
Check the documentation for [`git-aggregator`](https://github.com/acsone/git-aggregator) for more information, as that is the tool we use to manage the repos.
