### DISCUSSION TITLE
Unable to change backup dst inside backup container

### DISCUSSION THREAD

**Discussion by rquevedo** [Tecnativa/doodba#393] [Doodba - The template] [answered]
Hi folks,
Im initially set one backup DST for one production environment, lets say `mega://someuser@mega.nz/BACKUPS/Someclient`
Then few days ago i change this partner from initial domain to other, and backup service show this error:

```
Fatal Error: Backup source host has changed.
Current hostname: backup.www.somepartner.com
Previous hostname: backup.somepartner.mykubux.com
```

I decided change the folder to store backups from this partner and change in commons.yaml DST environment variable to: 

`mega://someuser@mega.nz/BACKUPS/SomeclientOtherFolder`

The thing is that DTS dont change inside my backup container, remain old value. I tried:

1. Rebuild container without cache `docker-compose build --pull --no-cache backup`
2. Remove build cache `docker builder prune --all`
3. Update values using copier update

**Comment by yajo** [comment, marked as answer]
Please post the results of running:

    docker-compose config

**Reply by rquevedo** [reply]
@Yajo This is the result of `docker-compose config`

```yaml
networks:
  default:
    driver_opts:
      encrypted: '1'
  inverseproxy_shared:
    external: true
    name: inverseproxy_shared
services:
  backup:
    build:
      context: /home/user/Pname/backup
    depends_on:
      db:
        condition: service_started
    domainname: www.pname.com
    environment:
      DST: mega://reisyreinier@mega.nz/BACKUPS/www.pname.com
      JOB_500_WHAT: dup full $$SRC $$DST
      JOB_500_WHEN: weekly
      JOB_800_WHAT: dup --force remove-older-than 3M $$DST
      JOB_800_WHEN: weekly
      PASSPHRASE: Kubux
      PGDATABASE: prod
      PGPASSWORD: somepassword
      PGUSER: odoo
      TZ: UTC
    hostname: backup
    image: pname/duplicity:postgres
    init: true
    restart: unless-stopped
    volumes:
    - filestore:/mnt/backup/src/odoo:z
    - backup_cache:/root:z
  db:
    environment:
      CONF_EXTRA: 'work_mem = 512MB

        '
      POSTGRES_DB: prod
      POSTGRES_PASSWORD: somepassword
      POSTGRES_USER: odoo
    image: ghcr.io/tecnativa/postgres-autoconf:13-alpine
    restart: unless-stopped
    shm_size: 512mb
    volumes:
    - db:/var/lib/postgresql/data:z
  odoo:
    build:
      args:
        GID: '1000'
        ODOO_VERSION: '13.0'
        UID: '1000'
      context: /home/user/Pname/odoo
    depends_on:
      db:
        condition: service_started
    environment:
      ADMIN_PASSWORD: somepassword
      DB_FILTER: .*
      DOODBA_ENVIRONMENT: prod
      EMAIL_FROM: ''
      INITIAL_LANG: es_ES
      PGDATABASE: prod
      PGPASSWORD: somepassword
      PGUSER: odoo
      PROXY_MODE: "true"
    labels:
      doodba.domain.main: www.pname.com
      traefik.alt-1.frontend.redirect.regex: ^(.*)://([^/]+)/(.*)$$
      traefik.alt-1.frontend.redirect.replacement: $$1://www.pname.com/$$3
      traefik.alt-1.frontend.rule: Host:pname.com
      traefik.backend.buffering.retryExpression: IsNetworkError() && Attempts() <
        5
      traefik.docker.network: inverseproxy_shared
      traefik.domain: www.pname.com
      traefik.enable: "true"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,
        nofollow
      traefik.forbiddenCrawlers-0.frontend.rule: Host:www.pname.com;Path:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}
      traefik.frontend.passHostHeader: "true"
      traefik.http.middlewares.Pname-13-0-prod-buffering.buffering.retryExpression: IsNetworkError()
        && Attempts() < 5
      traefik.http.middlewares.Pname-13-0-prod-compress.compress: "true"
      traefik.http.middlewares.Pname-13-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag: noindex,
        nofollow
      traefik.http.middlewares.Pname-13-0-prod-forceSecure.headers.forceSTSHeader: "true"
      traefik.http.middlewares.Pname-13-0-prod-forceSecure.headers.sslRedirect: "true"
      traefik.http.middlewares.Pname-13-0-prod-redirect-1.redirectRegex.regex: ^(.*)://([^/]+)/(.*)$$
      traefik.http.middlewares.Pname-13-0-prod-redirect-1.redirectRegex.replacement: $$1://www.pname.com/$$3
      traefik.http.routers.Pname-13-0-prod-forbiddenCrawlers-0.middlewares: Pname-13-0-prod-buffering,
        Pname-13-0-prod-compress, Pname-13-0-prod-forbid-crawlers, Pname-13-0-prod-forceSecure
      traefik.http.routers.Pname-13-0-prod-forbiddenCrawlers-0.rule: Host(`www.pname.com`)
        && (PathPrefix(`/web/`, `/website/info/`) || Path(`/web`, `/website/info`))
      traefik.http.routers.Pname-13-0-prod-forbiddenCrawlers-0.service: Pname-13-0-prod-main
      traefik.http.routers.Pname-13-0-prod-forbiddenCrawlers-secure-0.middlewares: Pname-13-0-prod-buffering,
        Pname-13-0-prod-compress, Pname-13-0-prod-forbid-crawlers, Pname-13-0-prod-forceSecure
      traefik.http.routers.Pname-13-0-prod-forbiddenCrawlers-secure-0.rule: Host(`www.pname.com`)
        && (PathPrefix(`/web/`, `/website/info/`) || Path(`/web`, `/website/info`))
      traefik.http.routers.Pname-13-0-prod-forbiddenCrawlers-secure-0.service: Pname-13-0-prod-main
      traefik.http.routers.Pname-13-0-prod-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.Pname-13-0-prod-forbiddenCrawlers-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.Pname-13-0-prod-longpolling-0.middlewares: Pname-13-0-prod-forceSecure
      traefik.http.routers.Pname-13-0-prod-longpolling-0.rule: Host(`www.pname.com`)
        && PathPrefix(`/longpolling/`)
      traefik.http.routers.Pname-13-0-prod-longpolling-0.service: Pname-13-0-prod-longpolling
      traefik.http.routers.Pname-13-0-prod-longpolling-secure-0.middlewares: Pname-13-0-prod-forceSecure
      traefik.http.routers.Pname-13-0-prod-longpolling-secure-0.rule: Host(`www.pname.com`)
        && PathPrefix(`/longpolling/`)
      traefik.http.routers.Pname-13-0-prod-longpolling-secure-0.service: Pname-13-0-prod-longpolling
      traefik.http.routers.Pname-13-0-prod-longpolling-secure-0.tls: "true"
      traefik.http.routers.Pname-13-0-prod-longpolling-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.Pname-13-0-prod-main-0.middlewares: Pname-13-0-prod-buffering,
        Pname-13-0-prod-compress, Pname-13-0-prod-forceSecure
      traefik.http.routers.Pname-13-0-prod-main-0.rule: Host(`www.pname.com`)
      traefik.http.routers.Pname-13-0-prod-main-0.service: Pname-13-0-prod-main
      traefik.http.routers.Pname-13-0-prod-main-secure-0.middlewares: Pname-13-0-prod-buffering,
        Pname-13-0-prod-compress, Pname-13-0-prod-forceSecure
      traefik.http.routers.Pname-13-0-prod-main-secure-0.rule: Host(`www.pname.com`)
      traefik.http.routers.Pname-13-0-prod-main-secure-0.service: Pname-13-0-prod-main
      traefik.http.routers.Pname-13-0-prod-main-secure-0.tls: "true"
      traefik.http.routers.Pname-13-0-prod-main-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.Pname-13-0-prod-redirect-1.middlewares: Pname-13-0-prod-compress,
        Pname-13-0-prod-forceSecure, Pname-13-0-prod-redirect-1
      traefik.http.routers.Pname-13-0-prod-redirect-1.rule: Host(`pname.com`)
      traefik.http.routers.Pname-13-0-prod-redirect-1.service: Pname-13-0-prod-main
      traefik.http.routers.Pname-13-0-prod-redirect-secure-1.middlewares: Pname-13-0-prod-compress,
        Pname-13-0-prod-forceSecure, Pname-13-0-prod-redirect-1
      traefik.http.routers.Pname-13-0-prod-redirect-secure-1.rule: Host(`pname.com`)
      traefik.http.routers.Pname-13-0-prod-redirect-secure-1.service: Pname-13-0-prod-main
      traefik.http.routers.Pname-13-0-prod-redirect-secure-1.tls: "true"
      traefik.http.routers.Pname-13-0-prod-redirect-secure-1.tls.certResolver: letsencrypt
      traefik.http.services.Pname-13-0-prod-longpolling.loadbalancer.server.port: '8072'
      traefik.http.services.Pname-13-0-prod-main.loadbalancer.server.port: '8069'
      traefik.longpolling-0.frontend.rule: Host:www.pname.com;Path:/longpolling/{anything:.*}
      traefik.longpolling-0.port: '8072'
      traefik.main-0.frontend.rule: Host:www.pname.com
      traefik.port: '8069'
    networks:
      default: {}
      inverseproxy_shared: {}
    restart: unless-stopped
    tty: true
    volumes:
    - filestore:/var/lib/odoo:z
version: '2.4'
volumes:
  backup_cache: {}
  db: {}
  filestore: {}

```
