### DISCUSSION TITLE
Error in Prod enviroment

### DISCUSSION THREAD

**Discussion by jaiodoo** [Tecnativa/doodba#395] [Q&A]
Hello,
I'm having trouble setting up a production environment
my copier-answare

```yml
# Changes here will be overwritten by Copier
_commit: v2.6.1
_src_path: gh:Tecnativa/doodba-copier-template
backup_deletion: false
backup_dst: null
backup_email_from: null
backup_email_to: null
backup_tz: UTC
cidr_whitelist: null
domains_prod:
- hosts:
  - www.mydomain.com
- hosts:
  - mydomain.com
  redirect_to: www.mydomain.com
domains_test: null
gitlab_url: null
odoo_dbfilter: .*
odoo_initial_lang: es_ES
odoo_listdb: false
odoo_oci_image: null
odoo_proxy: traefik
odoo_version: 14.0
paths_without_crawlers:
- /web
- /website/info
postgres_dbname: prod
postgres_username: odoo
postgres_version: 13
project_author: jaiodoo
project_license: BSL-1.0
project_name: project-name
smtp_canonical_default: null
smtp_canonical_domains: null
smtp_default_from: null
smtp_relay_host: null
smtp_relay_port: 587
smtp_relay_user: null
```

and when run
docker-compose -f prod.yaml up

```
db_1    | 
db_1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1    | 
odoo_1  | doodba INFO: Waiting until postgres is listening at db...
db_1    | 2021-03-01 00:52:26.001 GMT [1] LOG:  starting PostgreSQL 13.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit
db_1    | 2021-03-01 00:52:26.005 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1    | 2021-03-01 00:52:26.006 GMT [1] LOG:  listening on IPv6 address "::", port 5432
db_1    | 2021-03-01 00:52:26.022 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1    | 2021-03-01 00:52:26.038 GMT [20] LOG:  database system was interrupted; last known up at 2021-03-01 00:33:13 GMT
db_1    | 2021-03-01 00:52:26.078 GMT [20] LOG:  database system was not properly shut down; automatic recovery in progress
db_1    | 2021-03-01 00:52:26.089 GMT [20] LOG:  redo starts at 0/15E9CC8
db_1    | 2021-03-01 00:52:26.089 GMT [20] LOG:  invalid record length at 0/15E9D00: wanted 24, got 0
db_1    | 2021-03-01 00:52:26.089 GMT [20] LOG:  redo done at 0/15E9CC8
db_1    | 2021-03-01 00:52:26.142 GMT [1] LOG:  database system is ready to accept connections
db_1    | 2021-03-01 00:52:26.397 GMT [27] FATAL:  password authentication failed for user "odoo"
db_1    | 2021-03-01 00:52:26.397 GMT [27] DETAIL:  Role "odoo" does not exist.
db_1    | 	Connection matched pg_hba.conf line 8: "host all all 192.168.64.0/20 md5"
db_1    | 2021-03-01 00:52:27.467 GMT [28] FATAL:  password authentication failed for user "odoo"
db_1    | 2021-03-01 00:52:27.467 GMT [28] DETAIL:  Role "odoo" does not exist.
db_1    | 	Connection matched pg_hba.conf line 8: "host all all 192.168.64.0/20 md5"
db_1    | 2021-03-01 00:52:28.516 GMT [29] FATAL:  password authentication failed for user "odoo"
db_1    | 2021-03-01 00:52:28.516 GMT [29] DETAIL:  Role "odoo" does not exist.
db_1    | 	Connection matched pg_hba.conf line 8: "host all all 192.168.64.0/20 md5"
db_1    | 2021-03-01 00:52:29.566 GMT [30] FATAL:  password authentication failed for user "odoo"
db_1    | 2021-03-01 00:52:29.566 GMT [30] DETAIL:  Role "odoo" does not exist.
db_1    | 	Connection matched pg_hba.conf line 8: "host all all 192.168.64.0/20 md5"
db_1    | 2021-03-01 00:52:30.616 GMT [31] FATAL:  password authentication failed for user "odoo"
db_1    | 2021-03-01 00:52:30.616 GMT [31] DETAIL:  Role "odoo" does not exist.
db_1    | 	Connection matched pg_hba.conf line 8: "host all all 192.168.64.0/20 md5"
```
