### DISCUSSION TITLE
Openupgrade with doodba 2

### DISCUSSION THREAD

**Discussion by ygol** [Tecnativa/doodba#434] [Q&A]
I would like to use openupgrade with doodba. I found https://github.com/Tecnativa/doodba/discussions/410 but will need more details.

I am following [openupgrade documentation](https://oca.github.io/OpenUpgrade/migration_details.html)

0.  I build a new doodba project (odoo 14) to upgrade from v13.
1. Get the code from OpenUpgrade and dependencies

 **in repos.yaml**
./odoo:
```
  defaults:
    # Shallow repositories ($DEPTH_DEFAULT=1) are faster & thinner
    # You may need a bigger depth when merging PRs (use $DEPTH_MERGE
    # for a sane value of 100 commits)
    depth: $DEPTH_DEFAULT
  remotes:
    ocb: https://github.com/OCA/OCB.git
    odoo: https://github.com/odoo/odoo.git
    openupgrade: https://github.com/OCA/OpenUpgrade.git
  target: ocb $ODOO_VERSION
  merges:
    - ocb $ODOO_VERSION

```
**and in dependencies/pip.txt**
`git+https://github.com/OCA/openupgradelib.git@master`

2.  Check coverage of the migration scripts for your installed modules
Found https://oca.github.io/OpenUpgrade/modules130-140.html
    - Is it correct that there are no OCA modules already done for 13.0 -> 14.0 ?

3. Make a copy of the database to migrate
    - Prepared a dump.sql from the v13 db I am upgrading.

4. Adjust the configuration for Odoo and OpenUpgrade
    - Should I add a file under **my_doodba_project/odoo/custom/conf.d** ? if yes, what would go in that file?
    - How would I  update the command line parameters? Is there a file I add the flags or should I launch it with:
 `docker-compose run --rm odoo --update all --stop-after-init --load=base,web,openupgrade_framework`
    - How do I point to the database I am upgrading?

Thank you.

**Comment by joao-p-marques** [comment]
Hi!

All the steps seem correct, according to the OU documentation.

> Is it correct that there are no OCA modules already done for 13.0 -> 14.0?

AFAICS, there are some modules already done: https://github.com/OCA/OpenUpgrade/milestone/11

> Adjust the configuration for Odoo and OpenUpgrade

As per the OpenUpgrade documentation, the adjustments you need to do to the configuration files are to point to the correct database you want to migrate and to launch the update. In Doodba, there are several ways to do it, pretty much as you mention in the question:

1. You can always edit a configuration parameter by adding a file to `odoo/custom/conf.d`. These will be processed in order of precedence and will generate a single configuration file under `odoo/auto` in the container.
2. To change a command line parameter, you can either edit the `docker-compose.yaml` file and edit the `command` parameter in the `odoo` service, or you can override the command on a `docker-compose run` like you say in the example.

To point to the correct database, you can pass the specific parameter in the configuration file, `docker-compose.yaml` or `run` command, as said above. OTOH, you also need to make sure the `DB_FILTER` parameter matches that database, so that Odoo can "see" it.

I hope these quick suggestions have helped. However, maybe @Yajo or @pedrobaeza can give other guidelines or corrections, as they have more experience here.

**Reply by pedrobaeza** [reply]
On v14, there's a slight difference with other versions, as migration scripts are separated from Odoo code, so that migration scripts should be put available in any path and use the proper command line to use it as upgrade paths, but I haven't tried yet with any, as migration scripts for v14 are still in development.

**Reply by pleirb** [reply]
Does this have to do with the fact that the odoo folder is not listed in the openupgrade project for version 14 and later? What would it be like then to carry out the migration? I have migrated perfectly with Doodba up to version 13, but now I want to continue, I think I got addicted to migrating :)
There is some special configuration for repos.yaml?. At the moment I have configured with OCB, but only to test that it works.

**Reply by pedrobaeza** [reply]
A command for migrating may be:

```
docker-compose run --rm -l traefik.enable=false odoo --workers=0 -u all --load=base,web,openupgrade_framework --upgrade-path=/opt/odoo/auto/addons/openupgrade_scripts/scripts --stop-after-init
```

having in repos.yaml:

```
./openupgrade:
  defaults:
    depth: $DEPTH_DEFAULT
  remotes:
    openupgrade: https://github.com/OCA/OpenUpgrade.git
  target: openupgrade $ODOO_VERSION
  merges:
    - openupgrade $ODOO_VERSION
```

and in addons.yaml:

```
openupgrade:
  - openupgrade_framework
  - openupgrade_scripts
```
