### DISCUSSION TITLE
New instalation with doodba-copier-template in production error "Internal Server Error"

### DISCUSSION THREAD

**Discussion by JorgeQuinteros** [Tecnativa/doodba#440] [Doodba - The template] [answered]
Hello,
I have followed the steps to install an Odoo instance with dooba-copier-template:
https://github.com/Tecnativa/doodba-copier-template
https://github.com/Tecnativa/doodba-copier-template/blob/main/docs/daily-usage.md#production
But I am getting the following error:
![imagen](https://user-images.githubusercontent.com/43784849/131162915-7e1e8427-c67a-495c-8984-5a93ac18271a.png)

The log showed that I had to initialize the base, so I launched the commands recommended here but for production.
https://github.com/Tecnativa/doodba-copier-template/blob/main/docs/faq.md#why-is-odoo-saying-that-its-database-is-not-initialized
However this did not work, although I was no longer getting errors in the odoo log.
![Captura de pantalla 2021-08-27 183652](https://user-images.githubusercontent.com/43784849/131163358-29f4857c-bd55-4be6-891a-8ed7a57cf2bf.png)

I started to check the log of the other containers, and in the **inverseproxy_odoo_1** container I got the following:
![imagen](https://user-images.githubusercontent.com/43784849/131163687-12185a78-d529-4c7d-91fc-5ae5b5f490dd.png)

It definitely doesn't seem to be finding the **base module** so I updated the repositories to verify that it would **download Odoo OCB**, it seems that it does, however the same error kept coming up.
![imagen](https://user-images.githubusercontent.com/43784849/131164085-a186680a-0d6b-4069-a587-7bc997cb765f.png)

**In the folder structure I don't see that Odoo OCB has been downloaded**, if it was for permissions it would give error when doing buil --pull, right?
Do you know if there is any extra step to do that is not in the documentation? any help would be appreciated.

![imagen](https://user-images.githubusercontent.com/43784849/131164995-d509cc4d-defe-458f-b7b3-f1358c2ddae9.png)

Thanks,

**Comment by joao-p-marques** [comment, marked as answer]
Hi @JorgeQuinteros 

This seems like an error caused by having multiple databases in an instance, and when Odoo tries to access them, looks like at least one of them (`prod`) is not correctly initialized.

The first thing that might help you understand what is happening is taking a look at the different environments we use with Doodba Copier Template: We have a `devel`, a `test`, and a `prod` environment, each one corresponding to a different docker compose file. Each of the files will then be symlinked to `docker-compose.yaml`, so that you can interact with the containers without having to specify the file name each time. Taking a look at each of the files, you can also see that, depending on the environment, Odoo will access different databases. From what you said in the comment, I guess you are using the production one.

OTOH, the `invoke` tasks we have and that are mentioned in the docs are targeted at the development workflow, and they will sometimes change the symlink from `docker-compose.yaml` back to `devel.yaml`. So, if you are using those, you might be initializing one DB and then connecting to another from Odoo.

I also don’t understand what you mean when you mention the logs from 2 different Odoo containers, one showing everything correct, apparently, and the other saying that the `prod` DB was not correctly initialized. However, there should only be **one** Odoo container, so maybe check your running containers and docker compose files to see if there is something wrong there. 

I also have some doubts from seeing that you have another file (`inverseproxy.yaml`) in you project folder. It is true that this project relies on an inverse proxy (like Traefik) that should be created externally, but I wonder if some of its configurations might be causing the problem here. Can you provide its contents and explain a little more what you are doing command-wise?

Finally, you mention there might be an issue aggregating the repositories. Indeed, it is weird that no code appears in `odoo/ custom/src`. However, if you are seeing the logs you mention, then the Odoo code must be running somewhere, either in your machine, or coming from a pre-built image that includes that code.

**Reply by JorgeQuinteros** [reply]
Hello @joao-p-marques 
First of all, thank you very much for taking the time to read and answer. 

I did not use the invoke command precisely because I knew it was used for the development environment.

Regarding the two odoo containers, I am equally confused, probably I have made a mistake somewhere or maybe it is by wrongly launching the command to start the inverseproxy.yaml, as you said.
This is the content of the **inverseproxy.yaml** file(I got the content from here: https://github.com/Tecnativa/doodba-copier-template/blob/main/docs/faq.md#how-to-bootstrap-the-global-inverse-proxy):
And I execute it with: `docker-compose -f prod.yaml -p inverseproxy -f inverseproxy.yaml up -d`

```
version: "2.1"

services:
  proxy:
    image: traefik:1.6-alpine
    networks:
      shared:
      private:
      public:
    volumes:
      - acme:/etc/traefik/acme:rw,Z
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dockersocket
    restart: unless-stopped
    privileged: true
    tty: true
    command:
      - --ACME.ACMELogging
      - --ACME.Email=admin@nextodoo.com
      - --ACME.EntryPoint=https
      - --ACME.HTTPChallenge.entryPoint=http
      - --ACME.OnHostRule
      - --ACME.Storage=/etc/traefik/acme/acme.json
      - --DefaultEntryPoints=http,https
      - --EntryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --EntryPoints=Name:https Address::443 TLS
      - --LogLevel=INFO
      - --Docker
      - --Docker.EndPoint=http://dockersocket:2375
      - --Docker.ExposedByDefault=false
      - --Docker.Watch

  dockersocket:
    image: tecnativa/docker-socket-proxy
    privileged: true
    networks:
      private:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
    restart: unless-stopped

networks:
  shared:
    internal: true
    driver_opts:
      encrypted: 1

  private:
    internal: true
    driver_opts:
      encrypted: 1

  public:

volumes:
  acme:
```
**PD:**
![imagen](https://user-images.githubusercontent.com/43784849/131377602-e0655e3b-cb3b-4195-a14c-5f786a1af783.png)
I have checked the containers and I have clearly seen that **I have mistakenly created an extra Odoo container.** Probably because I lack more experience with docker and docker-compose
**I stopped it the extra odoo container** and restarted with `docker-compose restart` and it **worked correctly!**
![imagen](https://user-images.githubusercontent.com/43784849/131378012-7ed78bdc-a84f-41c6-ba53-91d0ade86f53.png)

Thank you very much again for responding, and we apologize for the inconvenience.
