### DISCUSSION TITLE
Traefik v2 Config

### DISCUSSION THREAD

**Discussion by rquevedo** [Tecnativa/doodba#475] [General]
Can anyone post inverseproxy.yaml for Traefik v2? No matter if is experimental  or not fully tested. I need test some features for a service running in same VPS with many doodba projects, but this service need Traefik v2 and currently running traefik is v1 with this config https://github.com/Tecnativa/doodba-copier-template/blob/main/docs/faq.md#how-to-bootstrap-the-global-inverse-proxy
Thanks in advance.

**Comment by pleirb** [comment]
> ¿Alguien puede publicar inverseproxy.yaml para Traefik v2? No importa si es experimental o no está completamente probado. Necesito probar algunas funciones para un servicio que se ejecuta en el mismo VPS con muchos proyectos doodba, pero este servicio necesita Traefik v2 y actualmente se ejecuta traefik v1 con esta configuración [https://github.com/Tecnativa/doodba-copier-template/blob/ main/docs/faq.md#how-to-bootstrap-the-global-inverse-proxy](https://github.com/Tecnativa/doodba-copier-template/blob/main/docs/faq.md#how-to-bootstrap-the-global-inverse-proxy) Gracias de antemano.

How are you? Do you have any news?

**Reply by rquevedo** [reply]
Hi, this is my config, still recently but working without problems so far. I have all configs inside traefik folder:
- config.yml
```
http:
  middlewares:
    buffering:
      buffering:
        retryExpression: IsNetworkError() && Attempts() < 5
    compress:
      compress: "true"
    secure:
      headers:
        forceSTSHeader: "true"
        sslRedirect: "true"
    nocrawlers:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "noindex, nofollow"
    doodba:
      chain:
        middlewares:
          - buffering
          - compress
          - secure
    localhost-only:
      ipWhitelist:
        sourceRange:
          - "127.0.0.1/32"
          - "10.11.0.0/16" # change to your docker subnet
    prod-headers:
      headers:
        customresponseHeaders:
          # In environment with versioned static files, switch commented
          # Cache-Control: "private,max-age=31536000"
          Cache-Control: "private,no-cache"
    test-headers:
      headers:
        customresponseHeaders:
          Cache-Control: "private,no-cache"
```
- traefik.yml

```
global:
  sendAnonymousUsage: false

providers:
  docker:
    endpoint: "http://dockersocket:2375"
    watch: true
    exposedByDefault: false
    network: traefik_shared

  file:
    filename: /etc/traefik/config.yml
    watch: true

# Uncomment for DEBUG logs
#log:
#  level: DEBUG

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    http:
      tls: "true"
    address: ":443"
api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "someemail@server.com"
      storage: "acme.json"
      # CA server to use.
      # UnComment the line to use Let's Encrypt's staging server
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      tlsChallenge: {}
```
- inverseproxy2.yaml

```
version: "3.8"

services:
  proxy:
    image: traefik:2.5
    networks:
      shared:
      private:
      public:
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dockersocket
    restart: unless-stopped
    privileged: true
    tty: true
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config.yml:/etc/traefik/config.yml:ro
      - ./certs:/etc/certs:rw,Z
      - acme:/etc/traefik/acme:rw,Z
    #
    # Note: when used in docker-compose.yml all dollar signs in the hash need to be doubled for escaping.
    # To create user:password pair, it's possible to use this command:
    # echo $(htpasswd -nB traefik-admin) | sed -e s/\\$/\\$\\$/g
    #
    # Also note that dollar signs should NOT be doubled when they not evaluated (e.g. Ansible docker_container module).
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=shared"
      - "traefik.http.routers.api.rule=Host(`some-subdomain-to-host-traefik-console.server.com`)"
      - "traefik.http.middlewares.auth.basicauth.users=traefik-admin:$$2y$$05$$CnP38WWlqbqk2Y.NG4CHM.DzkSc32aKfg7V.reGNLZxi4ngVXZcci"
      - "traefik.http.routers.api.tls.certResolver=letsencrypt"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"

  dockersocket:
    image: tecnativa/docker-socket-proxy
    privileged: true
    networks:
      private:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
    restart: unless-stopped

networks:
  shared:
    internal: true
    driver_opts:
      encrypted: 1

  private:
    internal: true
    driver_opts:
      encrypted: 1

  public:

volumes:
  acme:
```

To start the container:
`docker-compose -p inverseproxy -f inverseproxy2.yaml up -d`

In `inverseproxy2.yaml` file you need to change hostname and password to enable traefik console.
This config is mostly from https://github.com/Tecnativa/doodba-copier-template/issues/116

**Reply by pleirb** [reply]
Thank you very much, it is working for me too. I did tests by editing /etc/hots file and added a test domain and subdomain. Also generated a password with: `echo $(htpasswd -nB traefik-admin)` for a configuration file that corresponds to the traefik dashboard, and I saved it as one of the providers ("file") using the "directory" option, leaving it like this:

**dashboardtraefik.yml**
```
http:
  routers:
    api:
      rule: "Host(`dashboardtraefik.duckdns.org`)"
      entryPoints:
        - https
      service: api@internal
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$2y$05$MElxLD0JckEpAs4qowocR.is.rrecp6Qo2MnY02k.3NknJZRqF8rW"
```

**Reply by pleirb** [reply]
Well, now yes, everything working. I recommend [https://www.duckdns.org](https://www.duckdns.org) to create free test subdomains. What I am missing and would be perfect is some change in the Traefik 2 configuration to be able to access these domains on my intranet, at the moment I have no other option than to add these subdomains to my hosts file. If anyone has that setup, it would be greatly appreciated.

**Reply by pleirb** [reply]
> Bueno, ahora sí, todo funcionando. Recomiendo https://www.duckdns.org para crear subdominios de prueba gratuitos. Lo que me falta y sería perfecto es algún cambio en la configuración de Traefik 2 para poder acceder a estos dominios en mi intranet, de momento no tengo otra opción que agregar estos subdominios a mi archivo de hosts. Si alguien tiene esa configuración, se lo agradecería mucho.

Answering my own question, I know that it may not have much to do with Traefik, but it will surely help someone who wants to test production mode on an intranet managed by a Mikrotik Router with dynamic IP on the WAN. They also call it "fork". I leave you an image with the configurations that allowed me to do it
![Mikrotik](https://github.com/Tecnativa/doodba/assets/2092475/1c95261e-961d-4037-b194-fb400e76aaa4)

**Comment by pleirb** [comment]
On the other hand, I'd like to share the yaml that I'm currently working on with Traefik 2 inspired by the code of  @rquevedo, but with the modifications I've made, while everything works I'm not convinced it is the proper configuration and I must go to the experts to review. 

**docker-compose.yaml**
```
version: "3.8"
name: inverseproxy
services:

  traefik:
    container_name: traefik
    image: traefik:latest
    networks:
      shared: 
      private: 
      public: 
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dockersocket
    restart: unless-stopped
    privileged: true
    volumes:
      - ./traefik:/etc/traefik:rw,Z

  dockersocket:
    container_name: dockersocket
    image: tecnativa/docker-socket-proxy
    privileged: true
    networks:
      private:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
    restart: unless-stopped

networks:
  shared:
    internal: true
    driver_opts:
      encrypted: 1
  private:
    internal: true
    driver_opts:
      encrypted: 1
  public:
```

I run this simply with: **docker compose up -d**

And for Traefik I made the following file and folder structure:
```
traefik
  traefik.yml
  acme.json
  rules
    dashboardtraefik.yml
```

Where the Traefik configuration is the following:

**traefik.yml**
```
providers:
  docker:
    endpoint: "http://dockersocket:2375"
    watch: true
    exposedByDefault: false
  file:
    directory: /etc/traefik/rules
    watch: true

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    http:
      tls: "true"
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: pleirb@gmail.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: http
```
