### DISCUSSION TITLE
Issue with doodba 15 deployment (XmlHttpRequestError ?)

### DISCUSSION THREAD

**Discussion by jguenat** [Tecnativa/doodba#513] [Q&A]
Hello,

I have been using doodba for quite some time both in production and development and I find it very useful, thanks a lot.

I am facing an issue which I am having trouble to solve. Maybe you can help me?

On a production environment of odoo 15, I cannot open user preferences (where you can set-up your language, emai signature ...). The browser console show this error :
"Uncaught (in promise) Unable to render the required templates for the assets to load: XmlHttpRequestError Bad Request"
Note that i don't have this error in previous odoo versions. You can test it in the following url:
[doodba14.jguenat.ch](https://doodba14.jguenat.ch) (working as expected)
[doodba15.jguenat.ch](https://doodba15.jguenat.ch) (issue)
Both are "vanilla" doodba deployment with demo databases. i'm using the global inverse proxy traefik V1 docker-compose from the documentation.

<details>
<summary>Copier-answers for odoo 15.</summary>

```yaml
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.0
_src_path: gh:Tecnativa/doodba-copier-template
backup_deletion: false
backup_dst: null
backup_email_from: null
backup_email_to: null
backup_image_version: latest
backup_tz: UTC
cidr_whitelist: null
domains_prod:
- hosts:
  - doodba15.jguenat.ch
domains_test: null
gitlab_url: null
odoo_dbfilter: ^prod
odoo_initial_lang: fr_FR
odoo_listdb: true
odoo_oci_image: null
odoo_proxy: traefik
odoo_version: 15.0
paths_without_crawlers:
- /web
- /website/info
postgres_cidr_whitelist: null
postgres_dbname: prod
postgres_exposed: false
postgres_exposed_port: 5432
postgres_username: odoo
postgres_version: 13
project_author: jguenat
project_license: BSL-1.0
project_name: doodba15
smtp_canonical_default: null
smtp_canonical_domains: null
```

</details>

<details>
<summary>prod.yaml for odoo 15.</summary>

```yaml
version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "^prod"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "fr_FR"
    depends_on:
      - db
    networks:
      default:
      inverseproxy_shared:
    labels:
      doodba.domain.main: "doodba15.jguenat.ch"
      traefik.enable: "true"
      traefik.domain: "doodba15.jguenat.ch"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule: Host:doodba15.jguenat.ch;Path:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}
      traefik.main-0.frontend.rule: Host:doodba15.jguenat.ch
      traefik.longpolling-0.frontend.rule: Host:doodba15.jguenat.ch;Path:/longpolling/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.http.middlewares.doodba15-15-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.doodba15-15-0-prod-compress.compress: "true"
      ? traefik.http.middlewares.doodba15-15-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag
      : "noindex, nofollow"
      traefik.http.middlewares.doodba15-15-0-prod-forceSecure.headers.forceSTSHeader: "true"
      traefik.http.middlewares.doodba15-15-0-prod-forceSecure.headers.sslRedirect: "true"
      traefik.http.services.doodba15-15-0-prod-main.loadbalancer.server.port: 8069
      traefik.http.services.doodba15-15-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.doodba15-15-0-prod-main-0.rule:
        Host(`doodba15.jguenat.ch`)
      traefik.http.routers.doodba15-15-0-prod-main-0.service:
        doodba15-15-0-prod-main
      traefik.http.routers.doodba15-15-0-prod-main-0.middlewares:
        doodba15-15-0-prod-buffering, doodba15-15-0-prod-compress, doodba15-15-0-prod-forceSecure
      traefik.http.routers.doodba15-15-0-prod-main-secure-0.rule:
        Host(`doodba15.jguenat.ch`)
      traefik.http.routers.doodba15-15-0-prod-main-secure-0.service:
        doodba15-15-0-prod-main
      traefik.http.routers.doodba15-15-0-prod-main-secure-0.middlewares:
        doodba15-15-0-prod-buffering, doodba15-15-0-prod-compress, doodba15-15-0-prod-forceSecure
      traefik.http.routers.doodba15-15-0-prod-main-secure-0.tls: "true"
      traefik.http.routers.doodba15-15-0-prod-main-secure-0.tls.certResolver:
        letsencrypt
      traefik.http.routers.doodba15-15-0-prod-longpolling-0.rule:
        Host(`doodba15.jguenat.ch`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.doodba15-15-0-prod-longpolling-0.service:
        doodba15-15-0-prod-longpolling
      traefik.http.routers.doodba15-15-0-prod-longpolling-0.middlewares:
        doodba15-15-0-prod-forceSecure
      traefik.http.routers.doodba15-15-0-prod-longpolling-secure-0.rule:
        Host(`doodba15.jguenat.ch`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.doodba15-15-0-prod-longpolling-secure-0.service:
        doodba15-15-0-prod-longpolling
      traefik.http.routers.doodba15-15-0-prod-longpolling-secure-0.middlewares:
        doodba15-15-0-prod-forceSecure
      traefik.http.routers.doodba15-15-0-prod-longpolling-secure-0.tls: "true"
      traefik.http.routers.doodba15-15-0-prod-longpolling-secure-0.tls.certResolver:
        letsencrypt
      traefik.http.routers.doodba15-15-0-prod-forbiddenCrawlers-0.rule:
        Host(`doodba15.jguenat.ch`) && (PathPrefix(`/web/`, `/website/info/`) || Path(`/web`, `/website/info`))
      traefik.http.routers.doodba15-15-0-prod-forbiddenCrawlers-0.service:
        doodba15-15-0-prod-main
      traefik.http.routers.doodba15-15-0-prod-forbiddenCrawlers-0.middlewares:
        doodba15-15-0-prod-buffering, doodba15-15-0-prod-compress, doodba15-15-0-prod-forbid-crawlers, doodba15-15-0-prod-forceSecure
      traefik.http.routers.doodba15-15-0-prod-forbiddenCrawlers-secure-0.rule:
        Host(`doodba15.jguenat.ch`) && (PathPrefix(`/web/`, `/website/info/`) || Path(`/web`, `/website/info`))
      traefik.http.routers.doodba15-15-0-prod-forbiddenCrawlers-secure-0.service:
        doodba15-15-0-prod-main
      traefik.http.routers.doodba15-15-0-prod-forbiddenCrawlers-secure-0.middlewares:
        doodba15-15-0-prod-buffering, doodba15-15-0-prod-compress, doodba15-15-0-prod-forbid-crawlers, doodba15-15-0-prod-forceSecure
      traefik.http.routers.doodba15-15-0-prod-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.doodba15-15-0-prod-forbiddenCrawlers-secure-0.tls.certResolver:
        letsencrypt

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:
```

</details>

Also still having this issue #373 , you can see it there:
[doodba14test.jguenat.ch](https://doodba14test.jguenat.ch)

Thanks for your help.

Regards,
Julien

Edit : I switched to nginx and it solved my issues
