### DISCUSSION TITLE
Bus.bus is dead, long live the /websocket/ !

### DISCUSSION THREAD

**Discussion by yelizariev** [Tecnativa/doodba#530] [Q&A]
Does websocket work for you in Odoo 16? Asking for a friend...

**Comment by ap-wtioit** [comment]
We have it working on our systems with doodba.

from:
* https://github.com/odoo/odoo/pull/75510
* https://www.odoo.com/documentation/16.0/administration/install/deploy.html#livechat
if you are using nginx (https://nginx.org/en/docs/http/websocket.html):
```
map $http_upgrade $connection_upgrade {
    # https://nginx.org/en/docs/http/websocket.html
    default Upgrade;
    ''      Close;
}
```
```
proxy_pass http://odoo:8072;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
```

It did not work for me at all when:
* workers were not enabled
* dev mode was active

How i tested that it's working:
* have a database
* have 2 users (internal ones)
* install discuss / chat
* see if you can see each others messages without reloading

**Reply by yelizariev** [reply]
You are right, it doesn't work in dev mode, neither in "multi-thread mode" (i.e. without workers). Below is how I made it work in dev environment:

I updated my `devel.yaml` to open port 8072:

```yaml

services:
  odoo_proxy:
    image: ghcr.io/tecnativa/docker-whitelist:latest
    depends_on:
      - odoo
    networks: &public
      default:
      public:
    ports:
      - "127.0.0.1:16899:6899"
      - "127.0.0.1:16069:8069"
      - "127.0.0.1:16072:8072"
    environment:
      PORT: "6899 8069 8072"
      TARGET: odoo
```

And `command` for odoo service looks as following:

```yaml
    command:
      - odoo
      - --limit-memory-soft=0
      - --limit-time-real-cron=9999999
      - --limit-time-real=9999999
      - --workers=2
      #- --dev=reload,qweb,werkzeug,xml
      - --db-filter=devel
```

And then I made nginx config as in the docs
