### DISCUSSION TITLE
error running prod environment

### DISCUSSION THREAD

**Discussion by testpilot142** [Tecnativa/doodba#559] [Doodba - The template] [answered]
Hi,

First of all, thank you for do this project. It's a great tool to manage your odoo instances.

I was trying it in development and everything was fine. But when trying into production environment, I'm getting and error with odoo container. It keep restarting. I tried it on a clean doodba project with same result.

![Screenshot from 2023-08-22 13-03-16](https://github.com/Tecnativa/doodba/assets/142934458/55cc6137-4b5d-4cff-9176-647a622f5664)

Looking into the log for odoo instance, seems that odoo binary is not found, but not sure how to resolve this.
![Screenshot from 2023-08-22 13-04-07](https://github.com/Tecnativa/doodba/assets/142934458/be8293dc-e521-424d-a6ae-3aee742910ee)
I'm not an odoo or docker expert, but I think a clean instance with doodba image should run out of the box without error. So, maybe I'm missing something.
I just generate image with `invoke img-build`, run inverse proxy and then up docker compose with prod config.

This is my copier answers file
```yml
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v5.2.0
_src_path: gh:Tecnativa/doodba-copier-template
backup_deletion: false
backup_dst: ''
backup_email_from: None
backup_email_to: None
backup_image_version: latest
backup_tz: UTC
cidr_whitelist: null
domains_prod:
-   hosts: null
- prod.lvh.me
- company2.lvh.me
domains_test: null
gitlab_url: ''
odoo_dbfilter: '%d'
odoo_initial_lang: en_US
odoo_listdb: false
odoo_oci_image: ''
odoo_proxy: traefik
odoo_version: 15.0
paths_without_crawlers:
- /web
- /website/info
postgres_cidr_whitelist: null
postgres_dbname: prod
postgres_exposed: false
postgres_exposed_port: 5432
postgres_username: odoo
postgres_version: '15'
project_author: OdooDoomie
project_license: MIT
project_name: odoo-demo
smtp_canonical_default: None
smtp_canonical_domains: null
smtp_default_from: ''
smtp_relay_host: ''
smtp_relay_port: 587
smtp_relay_user: None
smtp_relay_version: '10'
```
I really appreciate if you can take a look and give me some thought into how can resolve this. If you need any additional config, let me know. Thanks in advance.
