### ISSUE TITLE
ssh config not being used in setup-devel

### ISSUE THREAD

**Issue by lreficent** [Tecnativa/doodba#225]
Let's say you have a ssh config file similar to this to use a secondary ssh key for a specific repo:

```bash
Host private.github.com
  User git
  Hostname github.com
  IdentityFile ~/.ssh/id_private_deploy
```

And you have a repo in the repos.yml similar to this:

```yml
./private:
    defaults:
        depth: $DEPTH_DEFAULT
    remotes:
        private: git@private.github.com:Eficent/private.git
    target:
        private $ODOO_VERSION
    merges:
        - private $ODOO_VERSION
```

Ok, with this setup, your images build without any problem fetching the code correctly. But when trying to autoaggregate the devel environment (setup-devel.yml) it fails. Even if I add a similar ssh config locally (which allows me to pull with the above remote name manually with no issues), it will fail when doing the setup-devel command.

Any advice/hint? How can I use the project or local ssh configuration during in the autoaggreagation?

Thank you!
