### ISSUE TITLE
[IDEAs] Client specific env vars

### ISSUE THREAD

**Issue by gdgellatly** [Tecnativa/doodba#252]
Hi,

I initially started using these to set nonconflicting ports in development as I'm often working multiple projects at once, but now I use them relatively extensively with Doodba.

The basic idea is to add a couple of extra ENV and ONBUILD ARG vars. 1 I call CLIENT_ID the other I call CLIENT_PROJECT . How I use them. 

Well CLIENT_ID is basically 3 digits used to set port numbers, e.g. odoo might run on 13001 for client 1 using odoo 13. Mail would be on say 9001 instead of 8025 (I used 9 because the 8's get crowded). But really only useful in development.

But CLIENT_PROJECT is more interesting. We use this mainly in image tags & repos.yaml. e.g. we can just declare a single client repo and use it everywhere and the clients private repo is installed.

```
./client:
  defaults:
    depth: $DEPTH_DEFAULT
  remotes:
    origin: <origin_path>/$CLIENT_PROJECT/addons.git
  target:
    origin $ODOO_VERSION
  merges:
    - origin $ODOO_VERSION
```
Obviously in addons.yaml using separate docs you can use there as well. 

However 1 thing we do do which I think is potentially also useful there is we have an ODOO_VARIANT variable. So if its C then web_responsive goes in, if its E then enterprise does using the ONLY flag.

**Comment by Yajo** [comment]
Those are good ideas, indeed, and they are a good showcase on how Doodba is so flexible! :wink:  


For your case, you can ship a default `addons.yaml` file with sections such as:

```yaml
---
ONLY:
  USES_ENTERPRISE: "1"
enterprise: ["*"]
---
ONLY:
  USES_WEB_RESPONSIVE: "1"
web:
- web_responsive
```

Then, you can override your scaffolding's [`odoo/Dockerfile`](https://github.com/Tecnativa/doodba-scaffolding/blob/f75d36ac141ede5dded989fcc158f9c02d143362/odoo/Dockerfile) and add:

```Dockerfile
ARG ODOO_VERSION
FROM tecnativa/doodba:${ODOO_VERSION}-onbuild
# XXX Change these depending on customer
ENV CLIENT_PROJECT=trololo
ENV CLIENT_ID=000
ENV USES_WEB_RESPONSIVE=1 USES_ENTERPRISE=1
```

And basically you're done.

Those variables are however very specific to your use case, and IMHO we shouldn't include them in the official scaffolding.

We have (and recommend having) our own private scaffolding, which applies our specific logic that anyone else wouldn't need or understand. This is possibly your case here.

Thanks for sharing the ideas, but closing for those reasons explained.
