### ISSUE TITLE
Merging addons.yaml and repos.yaml

### ISSUE THREAD

**Issue by yelizariev** [Tecnativa/doodba#256]
The two config files are interconnected and on editing one of them, you may need to update another one too. I suggest to combine them into one. 

The possible merging is keeping ``repos.yaml`` and add new attribute there.

Example:
```
/opt/odoo/custom/src/web:
  depth: $DEPTH_DEFAULT
  remotes:
    origin: https://github.com/OCA/web.git
  target: origin $ODOO_VERSION
  merges:
    - origin $ODOO_VERSION
  addons:
    - web_tree_many2one_clickable
    - web_environment_ribbon
      ONLY:
        PGDATABASE: # This environment variable must exist and be in the list
          - devel
          - test

```

As I understand ``git-aggregator`` will just ignore that attribute, while doodba can generate ``addons.yaml`` (or use such ``repos.yaml`` directly)

Example for ``repos.yaml`` with auto-generated part:

```
/opt/odoo/custom/src/web:
  addons:
    - module_auto_update
```

This would be converted to 

```
...

/opt/odoo/custom/src/server-tools:
  depth: $DEPTH_DEFAULT
  remotes:
    origin: https://github.com/OCA/server-tools.git
  target: origin $ODOO_VERSION
  merges:
    - origin $ODOO_VERSION
  addons:
    - module_auto_update
```
