### ISSUE TITLE
help with adding an addon repo 

### ISSUE THREAD

**Issue by chesty** [Tecnativa/doodba#270]
Hi, I'm fairly new to doodba and a fan. I'm having some issues and I can't work it out.

I have an addon hosted on a private server, my repo.yaml is

```yaml
Notify:
    defaults:
        depth: $DEPTH_DEFAULT
    remotes:
        origin: http://172.29.9.7:8898/notify
    target: origin master
    merges:
        - origin master
```
my addons.yaml is
```yaml
Notify:
    -   notify
```
I've added some other addons in different repos and those work fine, the addon in my repo works in that all the git commands work, but then 400-clean deletes it. 

The only difference I can see between my repo and the other repos that don't get added addons deleted is my repo has one addon and it's in the root directory of the git repo, whereas the others have many addons and they are in a subdirectory.

I'm not sure if I'm right, should it work if the git repo has the addon in the git root directory?

I hope you don't mind me opening an issue, I couldn't see any other way to ask.

**Comment by pedrobaeza** [comment]
Although your repo only contains one module, it should be inside a directory with the module name in your private repository. If not, the auto-cleaning system + automatic addons path won't work in Doodba.

**Comment by chesty** [comment]
ok thanks, appreciate it.

**Comment by Yajo** [comment]
Another option:

```yaml
# repos.yaml
notify/notify:
    defaults:
        depth: $DEPTH_DEFAULT
    remotes:
        origin: http://172.29.9.7:8898/notify
    target: origin master
    merges:
        - origin master

# addons.yaml
notify:
  - notify
```

I'm not sure if you'll need a build script with a mkdir instruction, though.
