### ISSUE TITLE
Question, how to freeze repositories?

### ISSUE THREAD

**Issue by JuanjoA** [Tecnativa/doodba#309]
Hi, first, thanks for this awesome work!
I'm not in favor of updating repositories automatically when I do git-aggregate.
So I see, to freeze versions, I must have indicated in _repos.yalm_ the specific commit of each OCA repo I want to use, example:
```
./connector-interfaces:
    remotes:
        oca:  https://github.com/OCA/connector-interfaces.git
        acsone:  https://github.com/acsone/connector-interfaces.git
    merges:
        - oca 6054de2c4e669f85cec380da90d746061967dc83
...
```
and them, delete from _addons.yalm_
Is this the right way to do it?
Thanks
