### ISSUE TITLE
[Feature Request] make repos.yaml file name configurable

### ISSUE THREAD

**Issue by obayit** [Tecnativa/doodba#345]
Why make `repos.yaml` file name configurable?

Allow running multiple environments (e.g: `prod.yaml` and `test.yaml`) from the same "scaffolding" directory but with different `repos.yaml` file.

This change assumes that running multiple environments from the same "scaffolding" directory is possible, and not discouraged.
But even if it is not recommended to do so, having one "scaffolding" directory for production, and another for "testing" then using the later to run multiple containers/instances with different `repos.yaml` file for each one requires this change.
Otherwise for every testing containers/instance an entire copy of the "scaffolding" directory is needed, just to change the `repos.yaml`!

**Comment by obayit** [comment]
Related question here, tecnativa/doodba-copier-template#179

**Comment by theangryangel** [comment]
Dumb question... why not just separate git branches? Or am I missing something?

**Comment by obayit** [comment]
@theangryangel you mean using an env variable in `repos.yaml`? like:
```
./my-custom-module:
  defaults:
    depth: $DEPTH_DEFAULT
  remotes:
    main: https://github.com/user/repo.git
  target: main $CUSTOM_MODULE_BRANCH
  merges:
    - main $CUSTOM_MODULE_BRANCH
```

Well... that can be a temporary solution, but testing PRs can be different, because the `production` branch can be a head of the `feature branch` by a few commits.

My intention here is staging a PR with a real database.
