### ISSUE TITLE
error "The Compose file './docker-compose.yml' is invalid"

### ISSUE THREAD

**Issue by luismata01** [Tecnativa/doodba#390]
Hi
When I try to deploy ODOO 14, in the moment that I run the command
docker-compose up
I receive this error
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.proxy_cdnjs_cloudflare_com.networks.default contains an invalid type, it should be an object, or a null

Can you help me please

**Comment by obayit** [comment]
In the file `devel.yaml`, make sure the cloudflare part looks like this:
```
  # Whitelist outgoing traffic for tests, reports, etc.
  proxy_cdnjs_cloudflare_com:
    image: tecnativa/whitelist
    networks:
      default:
        aliases:
          - cdnjs.cloudflare.com
      public:
    environment:
      TARGET: cdnjs.cloudflare.com
      PRE_RESOLVE: 1
```

It looks like you modified it by mistake.
