### ISSUE TITLE
[16.0] `addons` script puts `base` module in `extra` if specified in `addons.yaml`

### ISSUE THREAD

**Issue by aleuffre** [Tecnativa/doodba#545]
## Describe the bug

I like to list base Odoo modules in my `addons.yaml` (especially in order to avoid issues with the auto-installation of certain modules, l10n modules being the worst offenders due to a hook in `account`)

So my addons.yaml looks something like this

```yaml
# Base Odoo Modules

odoo/odoo/addons:
  - base

odoo/addons:
  - account
  - analytic
  - auth*
  - base_*
  - bus
  - calendar
  - contacts
[...]
  - web
  - web_editor
  - web_kanban_gauge
  - web_tour
  - web_unsplash
---
# Somehow needed for installation, even if not installed
odoo/addons:
  - hr
  - hr_timesheet
  - mass_mailing
  - mrp
  - project
  - stock
  - website
---
# OCA
server-brand:
  - disable_odoo_online
  - portal_odoo_debranding
  - remove_odoo_enterprise
[...] # Continues as normal
---
ONLY:
  DOODBA_ENVIRONMENT:
    - devel
    - test
web:
  - web_environment_ribbon
```

Up until version 14 (I didn't check 15) this worked fine. `docker compose run --rm odoo addons list --extra` returns all the OCA modules and only those. Though the `base` module isn't listed with the core modules (which I only just noticed now, testing before opening this issue, as I never use the `addons` script with `--core`)

In odoo 16, the same `addons` command with the same `addons.yaml` file lists the `base` module together with the extra modules.

## Workaround

~~I'm still testing but it seems like listing the base module under the `odoo/addons` key with the relative path works in both v14 and v16, and the `addons` command correctly lists the `base` module under `core` and not under `extra`~~

```yaml
odoo/addons:
  - ../odoo/addons/base
  - account
  - analytic
  - auth*
[...]
```

Update: Tried building the container with this, and the `400-clean` script gets stuck, presumably because it doesn't know how to handle the relative path.

I'm still investigating and I'm not sure about why the difference exists at the moment. ~~If my workaround is fine or even the intended way~~, I'd like to make a PR to update the documentation, at least.

I'd be happy to contribute a PR towards this, once I can investigate further and/or be pointed in the right direction.

Thank you for your time!
